---
- hosts: localhost
  tasks:
    - name: Fetch JSON data from government API
      ansible.builtin.uri:
        url: https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=x8kLltwpwX8pos1ygof89rGH5axzruRR8sIY310t&per_page=1
        return_content: yes
        headers:
          Accept: "application/json"
          Access-Control-Allow-Credentials: "true"
        timeout: 60
      register: api_response

    - name: Save JSON response to a file
      ansible.builtin.copy:
        content: "{{ api_response.content }}"
        dest: "/root/output.json"
      when: api_response is not none

    - name: Parse JSON response
      ansible.builtin.set_fact:
        parsed_response: "{{ api_response.content | from_json }}"

    - name: Display working_not_enrolled overall_count
      debug:
        msg: "working_not_enrolled overall_count: {{ parsed_response.highest['2_yr'].working_not_enrolled.overall_count }}"
