---

- hosts: dev
  connection: ssh

  tasks:
    - name: installing webserver
      yum: name=httpd state=present

    - name: Starting webserver
      service: name=httpd state=started

    - name: creating a file
      file: path="/var/www/html/index.html" state=touch

    - name: Adding data into the file
      copy:
        dest: "/var/www/html/index.html"
        content: |
          <h1> Hi Everyone </h1>
          <h2> I am practicing Ansible </h2>

...
